package UI;

import hotelpossystem.Customer;
import hotelpossystem.Order;
import hotelpossystem.Service;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lingyanjiang
 */
public class MainFrame extends javax.swing.JFrame {

    private static int from;
    private static int to;
    private Control control = new Control();
    private CardLayout b;
    private ArrayList <Service> customerService = new ArrayList();
    private Order order = Customer.getCustomerInstance().getCurrentOrder();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        menuPane1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secondPanel = new javax.swing.JPanel();
        contentTopPane = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        mainFlowPanel = new javax.swing.JPanel();
        selectTimePanel = new javax.swing.JPanel();
        jBtBack = new javax.swing.JButton();
        jBtConfirm = new javax.swing.JButton();
        jCbFrom = new javax.swing.JComboBox();
        jCbTo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLbWarning = new javax.swing.JLabel();
        bookRoomPane = new javax.swing.JPanel();
        jCBF = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableR = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jBtSearch = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jBtSelect = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCBT = new javax.swing.JComboBox();
        payPanel = new javax.swing.JPanel();
        paymentPanel = new javax.swing.JPanel();
        jBtCancel = new javax.swing.JButton();
        jBtPayByCard = new javax.swing.JButton();
        jBtPayByCash = new javax.swing.JButton();
        cashPane = new javax.swing.JPanel();
        jBtCancel1 = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTfQuantity = new javax.swing.JTextField();
        jLbDeal = new javax.swing.JLabel();
        jLbChange = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        cardPane = new javax.swing.JPanel();
        jBtCancel2 = new javax.swing.JButton();
        displayPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTfFund = new javax.swing.JTextField();
        jLbDeal1 = new javax.swing.JLabel();
        jLbBalance = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        renewRoom = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        servicePanel = new javax.swing.JPanel();
        ServicePanel = new javax.swing.JPanel();
        jBtFS = new javax.swing.JButton();
        jBtCS = new javax.swing.JButton();
        freeService = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jBtS8 = new javax.swing.JButton();
        jBtS9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCb12 = new javax.swing.JComboBox();
        jBt20 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jCb13 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jCb7 = new javax.swing.JComboBox();
        jBt10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        chargedService = new javax.swing.JPanel();
        jLbCS = new javax.swing.JLabel();
        jBtS6 = new javax.swing.JButton();
        jBtS7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCb11 = new javax.swing.JComboBox();
        jBt19 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCb10 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jCb6 = new javax.swing.JComboBox();
        jBt9 = new javax.swing.JButton();
        jCb = new javax.swing.JComboBox();
        jBt = new javax.swing.JButton();
        Order = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(235, 236, 238));
        setResizable(false);
        setSize(new java.awt.Dimension(857, 574));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPane.setBackground(new java.awt.Color(242, 195, 17));
        topPane.setPreferredSize(new java.awt.Dimension(857, 92));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        jLabel1.setText("X Hotel Self Serve System");

        javax.swing.GroupLayout topPaneLayout = new javax.swing.GroupLayout(topPane);
        topPane.setLayout(topPaneLayout);
        topPaneLayout.setHorizontalGroup(
            topPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPaneLayout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        topPaneLayout.setVerticalGroup(
            topPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPaneLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(topPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPane.setBackground(new java.awt.Color(235, 236, 238));
        mainPane.setForeground(new java.awt.Color(235, 236, 238));

        menuPane1.setBackground(new java.awt.Color(235, 236, 238));
        menuPane1.setForeground(new java.awt.Color(235, 236, 238));
        menuPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(235, 236, 238));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nroom.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 146, 161, 143));

        jButton2.setBackground(new java.awt.Color(235, 236, 238));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rroom.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        menuPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 146, 161, 143));

        jButton3.setBackground(new java.awt.Color(235, 236, 238));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nserv.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        menuPane1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 146, 161, 143));

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Book New Room");
        menuPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel3.setText("Renew Room");
        menuPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel4.setText("Book New Service");
        menuPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(menuPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(menuPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, -1, -1));

        secondPanel.setBackground(new java.awt.Color(235, 236, 238));
        secondPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentTopPane.setBackground(new java.awt.Color(235, 236, 238));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconorder.png"))); // NOI18N
        jLabel14.setText("View Order");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentTopPaneLayout = new javax.swing.GroupLayout(contentTopPane);
        contentTopPane.setLayout(contentTopPaneLayout);
        contentTopPaneLayout.setHorizontalGroup(
            contentTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentTopPaneLayout.createSequentialGroup()
                .addContainerGap(731, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(37, 37, 37))
        );
        contentTopPaneLayout.setVerticalGroup(
            contentTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentTopPaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        secondPanel.add(contentTopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, 50));

        mainFlowPanel.setBackground(new java.awt.Color(235, 236, 238));
        mainFlowPanel.setLayout(new java.awt.CardLayout());

        selectTimePanel.setBackground(new java.awt.Color(235, 236, 238));

        jBtBack.setText("back");
        jBtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtBackActionPerformed(evt);
            }
        });

        jBtConfirm.setText("Confirm");
        jBtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConfirmActionPerformed(evt);
            }
        });

        jCbFrom.setEditable(true);

        jCbTo.setEditable(true);

        jLabel7.setText("Check In");

        jLabel8.setText("Check out");

        jLbWarning.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N

        javax.swing.GroupLayout selectTimePanelLayout = new javax.swing.GroupLayout(selectTimePanel);
        selectTimePanel.setLayout(selectTimePanelLayout);
        selectTimePanelLayout.setHorizontalGroup(
            selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTimePanelLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtConfirm)
                    .addGroup(selectTimePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTimePanelLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jBtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(736, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTimePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLbWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        selectTimePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtBack, jBtConfirm});

        selectTimePanelLayout.setVerticalGroup(
            selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTimePanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jBtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectTimePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLbWarning)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                    .addComponent(jBtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        selectTimePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtBack, jBtConfirm});

        mainFlowPanel.add(selectTimePanel, "card3");
        control.intiateDate(jCbFrom, jCbTo, jLbWarning, from, to);

        bookRoomPane.setBackground(new java.awt.Color(235, 236, 238));

        jCBF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "all", "level1", "level2" }));

        jTableR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room number", "floor", "type", "price"
            }
        ));
        jScrollPane1.setViewportView(jTableR);

        jLabel5.setText("floor:");

        jBtSearch.setText("search");
        jBtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSearchActionPerformed(evt);
            }
        });

        jButton4.setText("back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jBtSelect.setText("Select");
        jBtSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSelectActionPerformed(evt);
            }
        });

        jLabel6.setText("Type:");

        jCBT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "all", "normal single", "normal double", "big single", "big double" }));

        javax.swing.GroupLayout bookRoomPaneLayout = new javax.swing.GroupLayout(bookRoomPane);
        bookRoomPane.setLayout(bookRoomPaneLayout);
        bookRoomPaneLayout.setHorizontalGroup(
            bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookRoomPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtSelect)
                .addGap(33, 33, 33))
            .addGroup(bookRoomPaneLayout.createSequentialGroup()
                .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookRoomPaneLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jBtSearch))
                    .addGroup(bookRoomPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookRoomPaneLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(79, 79, 79)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCBF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(535, Short.MAX_VALUE)))
        );

        bookRoomPaneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtSelect, jButton4});

        bookRoomPaneLayout.setVerticalGroup(
            bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookRoomPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookRoomPaneLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(26, 26, 26)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jCBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(306, Short.MAX_VALUE)))
        );

        bookRoomPaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtSelect, jButton4});

        mainFlowPanel.add(bookRoomPane, "card2");

        payPanel.setBackground(new java.awt.Color(235, 236, 238));
        payPanel.setLayout(new java.awt.CardLayout());

        paymentPanel.setBackground(new java.awt.Color(235, 236, 238));

        jBtCancel.setText("Cancel");
        jBtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelActionPerformed(evt);
            }
        });

        jBtPayByCard.setText("Pay by card");
        jBtPayByCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPayByCardActionPerformed(evt);
            }
        });

        jBtPayByCash.setText("Pay by cash");
        jBtPayByCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPayByCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jBtPayByCard, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jBtPayByCash, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtPayByCard, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPayByCash, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jBtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        payPanel.add(paymentPanel, "paymentcard");

        cashPane.setBackground(new java.awt.Color(235, 236, 238));
        cashPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtCancel1.setText("Cancel");
        jBtCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancel1ActionPerformed(evt);
            }
        });
        cashPane.add(jBtCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 375, 115, 39));

        displayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PaymentInfo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel11.setText("Deal");

        jLabel12.setText("Money Quantity");

        jLabel13.setText("Change");

        jLbDeal.setText("  ");

        jButton7.setText("CONFIRM");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbDeal)
                            .addComponent(jLbChange, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(89, 89, 89))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLbDeal))
                .addGap(35, 35, 35)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLbChange, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(26, 26, 26))
        );

        cashPane.add(displayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 330, 380));

        payPanel.add(cashPane, "cashPaneCard");

        cardPane.setBackground(new java.awt.Color(235, 236, 238));
        cardPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtCancel2.setText("Cancel");
        jBtCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancel2ActionPerformed(evt);
            }
        });
        cardPane.add(jBtCancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 375, 115, 39));

        displayPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PaymentInfo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel15.setText("Deal");

        jLabel16.setText("Available Fund");

        jLabel17.setText("Balance");

        jLbDeal1.setText("  ");

        jButton9.setText("CONFIRM");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayPanel1Layout = new javax.swing.GroupLayout(displayPanel1);
        displayPanel1.setLayout(displayPanel1Layout);
        displayPanel1Layout.setHorizontalGroup(
            displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbDeal1)
                            .addComponent(jLbBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(displayPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTfFund, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(89, 89, 89))
        );
        displayPanel1Layout.setVerticalGroup(
            displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLbDeal1))
                .addGap(35, 35, 35)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTfFund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLbBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(26, 26, 26))
        );

        cardPane.add(displayPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 330, 380));

        payPanel.add(cardPane, "cardPaneCard");

        mainFlowPanel.add(payPanel, "payCard");

        renewRoom.setBackground(new java.awt.Color(235, 236, 238));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Room number", "Check in date", "Check out date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton5.setText("Back");

        jButton6.setText("Confirm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout renewRoomLayout = new javax.swing.GroupLayout(renewRoom);
        renewRoom.setLayout(renewRoomLayout);
        renewRoomLayout.setHorizontalGroup(
            renewRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(renewRoomLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(65, 65, 65))
        );
        renewRoomLayout.setVerticalGroup(
            renewRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(renewRoomLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(renewRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        mainFlowPanel.add(renewRoom, "card5");

        servicePanel.setBackground(new java.awt.Color(235, 236, 238));
        servicePanel.setLayout(new java.awt.CardLayout());

        ServicePanel.setBackground(new java.awt.Color(235, 236, 238));
        ServicePanel.setPreferredSize(new java.awt.Dimension(770, 420));

        jBtFS.setText("Free Service");
        jBtFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFSActionPerformed(evt);
            }
        });

        jBtCS.setText("Charged Service");
        jBtCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicePanelLayout = new javax.swing.GroupLayout(ServicePanel);
        ServicePanel.setLayout(ServicePanelLayout);
        ServicePanelLayout.setHorizontalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicePanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jBtFS, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(270, 270, 270)
                .addComponent(jBtCS, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
        ServicePanelLayout.setVerticalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicePanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtCS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtFS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        servicePanel.add(ServicePanel, "serviceCard");

        freeService.setBackground(new java.awt.Color(235, 236, 238));
        freeService.setPreferredSize(new java.awt.Dimension(770, 420));

        jLabel9.setText("Free Service Lists:");

        jBtS8.setText("Back");
        jBtS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS8ActionPerformed(evt);
            }
        });

        jBtS9.setText("Next");
        jBtS9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS9ActionPerformed(evt);
            }
        });

        jPanel4.setPreferredSize(new java.awt.Dimension(350, 300));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb12ActionPerformed(evt);
            }
        });
        jPanel4.add(jCb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jBt20.setText("Add");
        jBt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt20ActionPerformed(evt);
            }
        });
        jPanel4.add(jBt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton8.setText("Confirm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jButton10.setText("Cancel");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jPanel5.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jCb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 260, 60));

        jPanel6.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb7ActionPerformed(evt);
            }
        });

        jBt10.setText("Add");
        jBt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBt10)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt10))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 64));

        jButton11.setText("Select");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel10.setText("Morning Call");

        javax.swing.GroupLayout freeServiceLayout = new javax.swing.GroupLayout(freeService);
        freeService.setLayout(freeServiceLayout);
        freeServiceLayout.setHorizontalGroup(
            freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(freeServiceLayout.createSequentialGroup()
                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(freeServiceLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(freeServiceLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel10)
                        .addGap(53, 53, 53)
                        .addComponent(jButton11))
                    .addGroup(freeServiceLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jBtS8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jBtS9)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        freeServiceLayout.setVerticalGroup(
            freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(freeServiceLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, freeServiceLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtS8)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, freeServiceLayout.createSequentialGroup()
                        .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(freeServiceLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtS9))
                            .addGroup(freeServiceLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jButton11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(250, 250, 250))))
        );

        servicePanel.add(freeService, "freeServiceCard");

        chargedService.setBackground(new java.awt.Color(235, 236, 238));
        chargedService.setPreferredSize(new java.awt.Dimension(770, 420));
        chargedService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbCS.setText("Charged Service");
        chargedService.add(jLbCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 144, 42));

        jBtS6.setText("Back");
        jBtS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS6ActionPerformed(evt);
            }
        });
        chargedService.add(jBtS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jBtS7.setText("Next");
        jBtS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS7ActionPerformed(evt);
            }
        });
        chargedService.add(jBtS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(350, 300));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb11ActionPerformed(evt);
            }
        });
        jPanel3.add(jCb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jBt19.setText("+");
        jBt19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt19ActionPerformed(evt);
            }
        });
        jPanel3.add(jBt19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton12.setText("Confirm");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jButton15.setText("Cancel");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jCb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 260, 60));

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb6ActionPerformed(evt);
            }
        });

        jBt9.setText("+");
        jBt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBt9)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt9))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 64));

        chargedService.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 620, 280));

        jCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Breakfast", "Lunch", "Super", "Laundry" }));
        chargedService.add(jCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 320, -1));

        jBt.setText("Choose");
        jBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtActionPerformed(evt);
            }
        });
        chargedService.add(jBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        servicePanel.add(chargedService, "chargedCard");

        mainFlowPanel.add(servicePanel, "card6");

        Order.setBackground(new java.awt.Color(235, 236, 238));
        Order.setPreferredSize(new java.awt.Dimension(860, 420));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Items", "Time", "Price"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jButton13.setText("Confirm");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Cancel");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(54, 54, 54)
                .addComponent(jButton14)
                .addGap(25, 25, 25))
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        mainFlowPanel.add(Order, "orderCard");

        secondPanel.add(mainFlowPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 860, 420));

        getContentPane().add(secondPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 860, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainPane.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //service button
        mainPane.setVisible(false);
        CardLayout c = (CardLayout)mainFlowPanel.getLayout(); 
        c.show(mainFlowPanel, "card6");
        
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        
        control.showDate(jCb6);
        control.showDate(jCb10);
        control.showDate(jCb11);
        control.showDate(jCb12);
        control.showDate(jCb7);
        control.showDate(jCb13);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSearchActionPerformed
        from=jCbFrom.getSelectedIndex(); 
        to=jCbTo.getSelectedIndex(); 
        control.activeSearch(jCBF, jCBT, jTableR, from, to);
    }//GEN-LAST:event_jBtSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout c = (CardLayout)mainFlowPanel.getLayout(); 
        c.show(mainFlowPanel, "card3");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtBackActionPerformed
        mainPane.setVisible(true);
    }//GEN-LAST:event_jBtBackActionPerformed

    private void jBtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConfirmActionPerformed
        CardLayout c = (CardLayout)mainFlowPanel.getLayout(); 
        c.show(mainFlowPanel, "card2");
        from = jCbFrom.getSelectedIndex();           
        to = jCbTo.getSelectedIndex(); 
        try {
            control.runn(jTableR, from, to);
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jBtConfirmActionPerformed

    private void jBtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelActionPerformed
        System.exit(0);   // TODO add your handling code here:
    }//GEN-LAST:event_jBtCancelActionPerformed

    private void jBtPayByCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPayByCardActionPerformed
        CardLayout c = (CardLayout)payPanel.getLayout(); 
        c.show(payPanel, "cashPaneCard");
    }//GEN-LAST:event_jBtPayByCardActionPerformed

    private void jBtPayByCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPayByCashActionPerformed
        CardLayout c = (CardLayout)payPanel.getLayout(); 
        c.show(payPanel, "cardPaneCard");
    }//GEN-LAST:event_jBtPayByCashActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mainPane.setVisible(false);
        CardLayout c = (CardLayout)mainFlowPanel.getLayout();
        c.show(mainFlowPanel, "card5");
        try {
            control.renewRoom(jTable1, "jly");
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        renewRoom.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jBtCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtCancel1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        control.confirmPay(jLbDeal, jTfQuantity, jLbChange);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jBtCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtCancel2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        control.confirmPay(jLbDeal, jTfFund, jLbBalance);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        new LogIn().setVisible(true);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "serviceCard");
        customerService.clear();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jBtFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFSActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "freeServiceCard");
    }//GEN-LAST:event_jBtFSActionPerformed

    private void jBtCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCSActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "chargedCard");
    }//GEN-LAST:event_jBtCSActionPerformed

    private void jBtS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS8ActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "serviceCard");
    }//GEN-LAST:event_jBtS8ActionPerformed

    private void jBtS9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS9ActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        int res = JOptionPane.showConfirmDialog(null, "Go to the charged service?", "", JOptionPane.YES_NO_OPTION);
        if (res == 0)
        b.show(servicePanel, "chargedCard");
        else {
            CardLayout c = (CardLayout)mainFlowPanel.getLayout();
        c.show(mainFlowPanel, "orderCard");
            order.addService(customerService);
            control.displayModel(jTable1, customerService, order);
        }
    }//GEN-LAST:event_jBtS9ActionPerformed

    private void jCb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb12ActionPerformed

    private void jBt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt20ActionPerformed
        jPanel6.setVisible(true);
    }//GEN-LAST:event_jBt20ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        customerService = control.getService(0, customerService, jPanel6, jPanel5, jCb12, jCb7, jCb13);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jCb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb13ActionPerformed

    private void jCb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb7ActionPerformed

    private void jBt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt10ActionPerformed
        jPanel5.setVisible(true);
    }//GEN-LAST:event_jBt10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jBtS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS6ActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "serviceCard");
    }//GEN-LAST:event_jBtS6ActionPerformed

    private void jBtS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS7ActionPerformed
        mainPane.setVisible(false);
        CardLayout c = (CardLayout)mainFlowPanel.getLayout();
        c.show(mainFlowPanel, "orderCard");
        order.addService(customerService);
        control.displayModel(jTable1, customerService, order);
    }//GEN-LAST:event_jBtS7ActionPerformed

    private void jCb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb11ActionPerformed

    private void jBt19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt19ActionPerformed
        jPanel1.setVisible(true);

    }//GEN-LAST:event_jBt19ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        customerService = control.serviceAdd(jCb, customerService, jPanel1, jPanel2, jCb11, jCb6, jCb10);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jCb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb10ActionPerformed

    private void jCb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb6ActionPerformed

    private void jBt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt9ActionPerformed
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jBt9ActionPerformed

    private void jBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtActionPerformed
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jBtActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        CardLayout c = (CardLayout)mainFlowPanel.getLayout();
        c.show(mainFlowPanel, "orderCard");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jBtSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Order;
    private javax.swing.JPanel ServicePanel;
    private javax.swing.JPanel bookRoomPane;
    private javax.swing.JPanel cardPane;
    private javax.swing.JPanel cashPane;
    private javax.swing.JPanel chargedService;
    private javax.swing.JPanel contentTopPane;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel displayPanel1;
    private javax.swing.JPanel freeService;
    private javax.swing.JButton jBt;
    private javax.swing.JButton jBt10;
    private javax.swing.JButton jBt19;
    private javax.swing.JButton jBt20;
    private javax.swing.JButton jBt9;
    private javax.swing.JButton jBtBack;
    private javax.swing.JButton jBtCS;
    private javax.swing.JButton jBtCancel;
    private javax.swing.JButton jBtCancel1;
    private javax.swing.JButton jBtCancel2;
    private javax.swing.JButton jBtConfirm;
    private javax.swing.JButton jBtFS;
    private javax.swing.JButton jBtPayByCard;
    private javax.swing.JButton jBtPayByCash;
    private javax.swing.JButton jBtS6;
    private javax.swing.JButton jBtS7;
    private javax.swing.JButton jBtS8;
    private javax.swing.JButton jBtS9;
    private javax.swing.JButton jBtSearch;
    private javax.swing.JButton jBtSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCBF;
    private javax.swing.JComboBox jCBT;
    private javax.swing.JComboBox jCb;
    private javax.swing.JComboBox jCb10;
    private javax.swing.JComboBox jCb11;
    private javax.swing.JComboBox jCb12;
    private javax.swing.JComboBox jCb13;
    private javax.swing.JComboBox jCb6;
    private javax.swing.JComboBox jCb7;
    private javax.swing.JComboBox jCbFrom;
    private javax.swing.JComboBox jCbTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbBalance;
    private javax.swing.JLabel jLbCS;
    private javax.swing.JLabel jLbChange;
    private javax.swing.JLabel jLbDeal;
    private javax.swing.JLabel jLbDeal1;
    private javax.swing.JLabel jLbWarning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableR;
    private javax.swing.JTextField jTfFund;
    private javax.swing.JTextField jTfQuantity;
    private javax.swing.JPanel mainFlowPanel;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel menuPane1;
    private javax.swing.JPanel payPanel;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JPanel renewRoom;
    private javax.swing.JPanel secondPanel;
    private javax.swing.JPanel selectTimePanel;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JPanel topPane;
    // End of variables declaration//GEN-END:variables
}
