package UI;

import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lingyanjiang
 */
public class MainFrame extends javax.swing.JFrame {

    private int from;
    private int to;
    private Control control = new Control();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        menuPane1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secondPanel = new javax.swing.JPanel();
        contentTopPane = new javax.swing.JPanel();
        mainFlowPanel = new javax.swing.JPanel();
        selectTimePanel = new javax.swing.JPanel();
        jBtBack = new javax.swing.JButton();
        jBtConfirm = new javax.swing.JButton();
        jCbFrom = new javax.swing.JComboBox();
        jCbTo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLbWarning = new javax.swing.JLabel();
        bookRoomPane = new javax.swing.JPanel();
        jCBF = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableR = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jBtSearch = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jBtSelect = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCBT = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(235, 236, 238));
        setResizable(false);
        setSize(new java.awt.Dimension(857, 574));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPane.setBackground(new java.awt.Color(242, 195, 17));
        topPane.setPreferredSize(new java.awt.Dimension(857, 92));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        jLabel1.setText("X Hotel Self Serve System");

        javax.swing.GroupLayout topPaneLayout = new javax.swing.GroupLayout(topPane);
        topPane.setLayout(topPaneLayout);
        topPaneLayout.setHorizontalGroup(
            topPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPaneLayout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        topPaneLayout.setVerticalGroup(
            topPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPaneLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(topPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPane.setBackground(new java.awt.Color(235, 236, 238));
        mainPane.setForeground(new java.awt.Color(235, 236, 238));

        menuPane1.setBackground(new java.awt.Color(235, 236, 238));
        menuPane1.setForeground(new java.awt.Color(235, 236, 238));
        menuPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(235, 236, 238));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nroom.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 146, 161, 143));

        jButton2.setBackground(new java.awt.Color(235, 236, 238));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rroom.png"))); // NOI18N
        jButton2.setBorder(null);
        menuPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 146, 161, 143));

        jButton3.setBackground(new java.awt.Color(235, 236, 238));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nserv.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        menuPane1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 146, 161, 143));

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Book New Room");
        menuPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel3.setText("Renew Room");
        menuPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel4.setText("Book New Service");
        menuPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(menuPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(menuPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, -1, -1));

        secondPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout contentTopPaneLayout = new javax.swing.GroupLayout(contentTopPane);
        contentTopPane.setLayout(contentTopPaneLayout);
        contentTopPaneLayout.setHorizontalGroup(
            contentTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        contentTopPaneLayout.setVerticalGroup(
            contentTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        secondPanel.add(contentTopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, 50));

        mainFlowPanel.setLayout(new java.awt.CardLayout());

        jBtBack.setText("back");
        jBtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtBackActionPerformed(evt);
            }
        });

        jBtConfirm.setText("Confirm");
        jBtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConfirmActionPerformed(evt);
            }
        });

        jCbFrom.setEditable(true);

        jCbTo.setEditable(true);

        jLabel7.setText("Check In");

        jLabel8.setText("Check out");

        jLbWarning.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N

        javax.swing.GroupLayout selectTimePanelLayout = new javax.swing.GroupLayout(selectTimePanel);
        selectTimePanel.setLayout(selectTimePanelLayout);
        selectTimePanelLayout.setHorizontalGroup(
            selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTimePanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectTimePanelLayout.createSequentialGroup()
                    .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTimePanelLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jBtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtConfirm)
                            .addGap(71, 71, 71))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTimePanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLbWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        selectTimePanelLayout.setVerticalGroup(
            selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTimePanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectTimePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLbWarning)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                    .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        mainFlowPanel.add(selectTimePanel, "card3");
        control.intiateDate(jCbFrom, jCbTo, jLbWarning, from, to);

        jCBF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "all", "level1", "level2" }));

        jTableR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room number", "floor", "type", "price"
            }
        ));
        jScrollPane1.setViewportView(jTableR);

        jLabel5.setText("floor:");

        jBtSearch.setText("search");
        jBtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSearchActionPerformed(evt);
            }
        });

        jButton4.setText("back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jBtSelect.setText("Select");

        jLabel6.setText("Type:");

        jCBT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "all", "normal single", "normal double", "big single", "big double" }));

        javax.swing.GroupLayout bookRoomPaneLayout = new javax.swing.GroupLayout(bookRoomPane);
        bookRoomPane.setLayout(bookRoomPaneLayout);
        bookRoomPaneLayout.setHorizontalGroup(
            bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookRoomPaneLayout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jBtSearch)
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookRoomPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bookRoomPaneLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(79, 79, 79)
                            .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCBF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(54, 529, Short.MAX_VALUE))
                        .addGroup(bookRoomPaneLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtSelect)
                            .addGap(64, 64, 64))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        bookRoomPaneLayout.setVerticalGroup(
            bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookRoomPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookRoomPaneLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(26, 26, 26)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jCBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        mainFlowPanel.add(bookRoomPane, "card2");

        secondPanel.add(mainFlowPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 860, 420));

        getContentPane().add(secondPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 860, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainPane.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSearchActionPerformed

        control.activeSearch(jCBF, jCBT, jTableR, jCBF.getSelectedIndex(), jCBT.getSelectedIndex());
    }//GEN-LAST:event_jBtSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //跳转
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtBackActionPerformed
        //跳转
    }//GEN-LAST:event_jBtBackActionPerformed

    private void jBtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConfirmActionPerformed
        CardLayout c = (CardLayout)mainFlowPanel.getLayout(); 
        c.show(mainFlowPanel, "card2");
    }//GEN-LAST:event_jBtConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookRoomPane;
    private javax.swing.JPanel contentTopPane;
    private javax.swing.JButton jBtBack;
    private javax.swing.JButton jBtConfirm;
    private javax.swing.JButton jBtSearch;
    private javax.swing.JButton jBtSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jCBF;
    private javax.swing.JComboBox jCBT;
    private javax.swing.JComboBox jCbFrom;
    private javax.swing.JComboBox jCbTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbWarning;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableR;
    private javax.swing.JPanel mainFlowPanel;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel menuPane1;
    private javax.swing.JPanel secondPanel;
    private javax.swing.JPanel selectTimePanel;
    private javax.swing.JPanel topPane;
    // End of variables declaration//GEN-END:variables
}
