package UI;

import hotelpossystem.Customer;
import hotelpossystem.Observer;
import hotelpossystem.Order;
import hotelpossystem.PayByCard;
import hotelpossystem.PayByCash;
import hotelpossystem.Payment;
import hotelpossystem.PaymentFactory;
import hotelpossystem.Room;
import hotelpossystem.Service;
import hotelpossystem.Time;
import hotelpossystem.dao.DAOFactory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lingyanjiang
 */
public class MainFrame extends javax.swing.JFrame implements Observer {

    public static int from;
    public static int to;
    private Control control = new Control();
    private CardLayout b;
    private ArrayList <Service> customerService = new ArrayList();
    private Order order = Customer.getCustomerInstance().getCurrentOrder();
    private Room room=new Room();
    private Payment payment;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        menuPane1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secondPanel = new javax.swing.JPanel();
        contentTopPane = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        mainFlowPanel = new javax.swing.JPanel();
        selectTimePanel = new javax.swing.JPanel();
        jBtBack = new javax.swing.JButton();
        jBtConfirm = new javax.swing.JButton();
        jCbFrom = new javax.swing.JComboBox();
        jCbTo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLbWarning = new javax.swing.JLabel();
        bookRoomPane = new javax.swing.JPanel();
        jCBF = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableR = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jBtSearch = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jBtSelect = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCBT = new javax.swing.JComboBox();
        payPanel = new javax.swing.JPanel();
        paymentPanel = new javax.swing.JPanel();
        jBtCancel = new javax.swing.JButton();
        jBtPayByCard = new javax.swing.JButton();
        jBtPayByCash = new javax.swing.JButton();
        cashPane = new javax.swing.JPanel();
        jBtCancel1 = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTfQuantity = new javax.swing.JTextField();
        jLbDeal = new javax.swing.JLabel();
        jLbChange = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabelTaxCash = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelCashTotal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        cardPane = new javax.swing.JPanel();
        jBtCancel2 = new javax.swing.JButton();
        displayPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLbDeal1 = new javax.swing.JLabel();
        jLbBalance = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabelTaxCard = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabelCard = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        renewRoom = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRenew = new javax.swing.JTable();
        jButtonRenewBack = new javax.swing.JButton();
        jButtonRenewConfirm = new javax.swing.JButton();
        servicePanel = new javax.swing.JPanel();
        ServicePanel = new javax.swing.JPanel();
        jBtFS = new javax.swing.JButton();
        jBtCS = new javax.swing.JButton();
        freeService = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jBtS8 = new javax.swing.JButton();
        jBtS9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCb12 = new javax.swing.JComboBox();
        jBt20 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jCb13 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jCb7 = new javax.swing.JComboBox();
        jBt10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        chargedService = new javax.swing.JPanel();
        jLbCS = new javax.swing.JLabel();
        jBtS6 = new javax.swing.JButton();
        jBtS7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCb11 = new javax.swing.JComboBox();
        jBt19 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCb10 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jCb6 = new javax.swing.JComboBox();
        jBt9 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jCb = new javax.swing.JComboBox();
        jBt = new javax.swing.JButton();
        Order = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jButtonOrderConfirm = new javax.swing.JButton();
        jButtonOrderCancel = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        receiptPane = new javax.swing.JPanel();
        requestPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        printPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(235, 236, 238));
        setResizable(false);
        setSize(new java.awt.Dimension(857, 574));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPane.setBackground(new java.awt.Color(242, 195, 17));
        topPane.setPreferredSize(new java.awt.Dimension(857, 92));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        jLabel1.setText("X Hotel Self Serve System");

        javax.swing.GroupLayout topPaneLayout = new javax.swing.GroupLayout(topPane);
        topPane.setLayout(topPaneLayout);
        topPaneLayout.setHorizontalGroup(
            topPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPaneLayout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        topPaneLayout.setVerticalGroup(
            topPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPaneLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(topPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPane.setBackground(new java.awt.Color(235, 236, 238));
        mainPane.setForeground(new java.awt.Color(235, 236, 238));

        menuPane1.setBackground(new java.awt.Color(235, 236, 238));
        menuPane1.setForeground(new java.awt.Color(235, 236, 238));
        menuPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(235, 236, 238));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nroom.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 146, 161, 143));

        jButton2.setBackground(new java.awt.Color(235, 236, 238));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rroom.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        menuPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 146, 161, 143));

        jButton3.setBackground(new java.awt.Color(235, 236, 238));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nserv.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        menuPane1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 146, 161, 143));

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Book New Room");
        menuPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel3.setText("Renew Room");
        menuPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel4.setText("Book New Service");
        menuPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(menuPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(menuPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, -1, -1));

        secondPanel.setBackground(new java.awt.Color(235, 236, 238));
        secondPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentTopPane.setBackground(new java.awt.Color(235, 236, 238));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconorder.png"))); // NOI18N
        jLabel14.setText("View Order");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel23.setText("Main Menu");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentTopPaneLayout = new javax.swing.GroupLayout(contentTopPane);
        contentTopPane.setLayout(contentTopPaneLayout);
        contentTopPaneLayout.setHorizontalGroup(
            contentTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentTopPaneLayout.createSequentialGroup()
                .addContainerGap(645, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(37, 37, 37))
        );
        contentTopPaneLayout.setVerticalGroup(
            contentTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentTopPaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(contentTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel23))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        secondPanel.add(contentTopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, 50));

        mainFlowPanel.setBackground(new java.awt.Color(235, 236, 238));
        mainFlowPanel.setLayout(new java.awt.CardLayout());

        selectTimePanel.setBackground(new java.awt.Color(235, 236, 238));

        jBtBack.setText("back");
        jBtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtBackActionPerformed(evt);
            }
        });

        jBtConfirm.setText("Confirm");
        jBtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConfirmActionPerformed(evt);
            }
        });

        jCbFrom.setEditable(true);

        jCbTo.setEditable(true);

        jLabel7.setText("Check In");

        jLabel8.setText("Check out");

        jLbWarning.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N

        javax.swing.GroupLayout selectTimePanelLayout = new javax.swing.GroupLayout(selectTimePanel);
        selectTimePanel.setLayout(selectTimePanelLayout);
        selectTimePanelLayout.setHorizontalGroup(
            selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTimePanelLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtConfirm)
                    .addGroup(selectTimePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTimePanelLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jBtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(736, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTimePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLbWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        selectTimePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtBack, jBtConfirm});

        selectTimePanelLayout.setVerticalGroup(
            selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTimePanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jBtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(selectTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectTimePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLbWarning)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                    .addComponent(jBtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        selectTimePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtBack, jBtConfirm});

        mainFlowPanel.add(selectTimePanel, "card3");
        control.intiateDate(jCbFrom, jCbTo, jLbWarning, from, to);

        bookRoomPane.setBackground(new java.awt.Color(235, 236, 238));

        jCBF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "all", "level1", "level2" }));

        jTableR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room number", "floor", "type", "price"
            }
        ));
        jScrollPane1.setViewportView(jTableR);

        jLabel5.setText("floor:");

        jBtSearch.setText("search");
        jBtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSearchActionPerformed(evt);
            }
        });

        jButton4.setText("back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jBtSelect.setText("Select");
        jBtSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSelectActionPerformed(evt);
            }
        });

        jLabel6.setText("Type:");

        jCBT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "all", "normal single", "normal double", "big single", "big double" }));

        javax.swing.GroupLayout bookRoomPaneLayout = new javax.swing.GroupLayout(bookRoomPane);
        bookRoomPane.setLayout(bookRoomPaneLayout);
        bookRoomPaneLayout.setHorizontalGroup(
            bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookRoomPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtSelect)
                .addGap(33, 33, 33))
            .addGroup(bookRoomPaneLayout.createSequentialGroup()
                .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookRoomPaneLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jBtSearch))
                    .addGroup(bookRoomPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookRoomPaneLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(79, 79, 79)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCBF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(535, Short.MAX_VALUE)))
        );

        bookRoomPaneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtSelect, jButton4});

        bookRoomPaneLayout.setVerticalGroup(
            bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookRoomPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookRoomPaneLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(26, 26, 26)
                    .addGroup(bookRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jCBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(306, Short.MAX_VALUE)))
        );

        bookRoomPaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtSelect, jButton4});

        mainFlowPanel.add(bookRoomPane, "card2");

        payPanel.setBackground(new java.awt.Color(235, 236, 238));
        payPanel.setLayout(new java.awt.CardLayout());

        paymentPanel.setBackground(new java.awt.Color(235, 236, 238));

        jBtCancel.setText("Cancel");
        jBtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelActionPerformed(evt);
            }
        });

        jBtPayByCard.setText("Pay by card");
        jBtPayByCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPayByCardActionPerformed(evt);
            }
        });

        jBtPayByCash.setText("Pay by cash");
        jBtPayByCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPayByCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jBtPayByCard, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jBtPayByCash, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtPayByCard, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPayByCash, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jBtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        payPanel.add(paymentPanel, "paymentcard");

        cashPane.setBackground(new java.awt.Color(235, 236, 238));
        cashPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtCancel1.setText("Cancel");
        jBtCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancel1ActionPerformed(evt);
            }
        });
        cashPane.add(jBtCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 375, 115, 39));

        displayPanel.setBackground(new java.awt.Color(235, 236, 238));
        displayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PaymentInfo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel11.setText("Deal:");

        jLabel12.setText("Paid:");

        jLabel13.setText("Change");

        jLbDeal.setText("  ");

        jButton7.setText("CONFIRM");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel26.setText("Tax:");

        jLabel30.setText("Total:");

        jLabelCashTotal.setText("");

        jLabel17.setText("Please insert bills");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbDeal, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabelTaxCash, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jTfQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jLbChange, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabelCashTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(100, 100, 100))))
        );

        displayPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelTaxCash, jLbChange, jLbDeal, jTfQuantity});

        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLbDeal))
                .addGap(7, 7, 7)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26)
                    .addComponent(jLabelTaxCash, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabelCashTotal))
                .addGap(5, 5, 5)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLbChange, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(26, 26, 26))
        );

        displayPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelCashTotal, jLabelTaxCash, jLbChange, jLbDeal, jTfQuantity});

        cashPane.add(displayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 330, 380));

        jButton13.setText("Back");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        cashPane.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 369, 110, 40));

        payPanel.add(cashPane, "cashPaneCard");

        cardPane.setBackground(new java.awt.Color(235, 236, 238));
        cardPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtCancel2.setText("Cancel");
        jBtCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancel2ActionPerformed(evt);
            }
        });
        cardPane.add(jBtCancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 375, 115, 39));

        displayPanel1.setBackground(new java.awt.Color(235, 236, 238));
        displayPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PaymentInfo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel15.setText("Deal:");

        jLbDeal1.setText("  ");

        jButton9.setText("Swipe Card");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel28.setText("Tax:");

        jLabelTaxCard.setText("");

        jLabel32.setText("Total:");

        jLabel16.setText("Please swipe your card");

        javax.swing.GroupLayout displayPanel1Layout = new javax.swing.GroupLayout(displayPanel1);
        displayPanel1.setLayout(displayPanel1Layout);
        displayPanel1Layout.setHorizontalGroup(
            displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbDeal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTaxCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(displayPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton9)))
                .addGap(95, 95, 95))
        );

        displayPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelTaxCard, jLbBalance, jLbDeal1});

        displayPanel1Layout.setVerticalGroup(
            displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLbDeal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabelTaxCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(displayPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(jLbBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        displayPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelCard, jLabelTaxCard, jLbBalance, jLbDeal1});

        cardPane.add(displayPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 330, 380));

        jButton14.setText("Back");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        cardPane.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 369, 110, 40));

        payPanel.add(cardPane, "cardPaneCard");

        mainFlowPanel.add(payPanel, "payCard");

        renewRoom.setBackground(new java.awt.Color(235, 236, 238));

        jTableRenew.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Room number", "Price", "Check in date", "Check out date"
            }
        ));
        jScrollPane2.setViewportView(jTableRenew);

        jButtonRenewBack.setText("Back");
        jButtonRenewBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenewBackActionPerformed(evt);
            }
        });

        jButtonRenewConfirm.setText("Confirm");
        jButtonRenewConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenewConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout renewRoomLayout = new javax.swing.GroupLayout(renewRoom);
        renewRoom.setLayout(renewRoomLayout);
        renewRoomLayout.setHorizontalGroup(
            renewRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(renewRoomLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButtonRenewBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRenewConfirm)
                .addGap(65, 65, 65))
        );
        renewRoomLayout.setVerticalGroup(
            renewRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(renewRoomLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(renewRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRenewConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRenewBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        mainFlowPanel.add(renewRoom, "card5");

        servicePanel.setBackground(new java.awt.Color(235, 236, 238));
        servicePanel.setLayout(new java.awt.CardLayout());

        ServicePanel.setBackground(new java.awt.Color(235, 236, 238));
        ServicePanel.setPreferredSize(new java.awt.Dimension(770, 420));

        jBtFS.setText("Free Service");
        jBtFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFSActionPerformed(evt);
            }
        });

        jBtCS.setText("Charged Service");
        jBtCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicePanelLayout = new javax.swing.GroupLayout(ServicePanel);
        ServicePanel.setLayout(ServicePanelLayout);
        ServicePanelLayout.setHorizontalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicePanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jBtFS, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(270, 270, 270)
                .addComponent(jBtCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
        ServicePanelLayout.setVerticalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicePanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtCS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtFS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        servicePanel.add(ServicePanel, "serviceCard");

        freeService.setBackground(new java.awt.Color(235, 236, 238));
        freeService.setPreferredSize(new java.awt.Dimension(770, 420));
        freeService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Free Service: ");
        freeService.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 117, 33));

        jBtS8.setText("Back");
        jBtS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS8ActionPerformed(evt);
            }
        });
        freeService.add(jBtS8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        jBtS9.setText("Next");
        jBtS9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS9ActionPerformed(evt);
            }
        });
        freeService.add(jBtS9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        jPanel4.setBackground(new java.awt.Color(235, 236, 238));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 300));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb12ActionPerformed(evt);
            }
        });
        jPanel4.add(jCb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jBt20.setText("Add more");
        jBt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt20ActionPerformed(evt);
            }
        });
        jPanel4.add(jBt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton8.setText("Confirm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jButton10.setText("Cancel");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jPanel5.setBackground(new java.awt.Color(235, 236, 238));
        jPanel5.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jCb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 260, 60));

        jPanel6.setBackground(new java.awt.Color(235, 236, 238));
        jPanel6.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb7ActionPerformed(evt);
            }
        });

        jBt10.setText("Add more");
        jBt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBt10)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt10))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 64));

        jLabel20.setText("Please select date for your service:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        freeService.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 450, 280));

        jButton11.setText("Select");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        freeService.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 90, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Morning Call");
        freeService.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        servicePanel.add(freeService, "freeServiceCard");

        chargedService.setBackground(new java.awt.Color(235, 236, 238));
        chargedService.setPreferredSize(new java.awt.Dimension(770, 420));
        chargedService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbCS.setText("Charged Service");
        chargedService.add(jLbCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 144, 42));

        jBtS6.setText("Back");
        jBtS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS6ActionPerformed(evt);
            }
        });
        chargedService.add(jBtS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jBtS7.setText("Next");
        jBtS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS7ActionPerformed(evt);
            }
        });
        chargedService.add(jBtS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        jPanel3.setBackground(new java.awt.Color(235, 236, 238));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 300));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb11ActionPerformed(evt);
            }
        });
        jPanel3.add(jCb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jBt19.setText("Add more");
        jBt19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt19ActionPerformed(evt);
            }
        });
        jPanel3.add(jBt19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton12.setText("Confirm");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jButton15.setText("Cancel");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(235, 236, 238));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jCb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 260, 60));

        jPanel1.setBackground(new java.awt.Color(235, 236, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb6ActionPerformed(evt);
            }
        });

        jBt9.setText("Add more");
        jBt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBt9)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt9))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 64));

        jLabel19.setText("Please select date for your service:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        chargedService.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 450, 280));

        jCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Breakfast", "Lunch", "Super", "Laundry" }));
        chargedService.add(jCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 320, -1));

        jBt.setText("Choose");
        jBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtActionPerformed(evt);
            }
        });
        chargedService.add(jBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        servicePanel.add(chargedService, "chargedCard");

        mainFlowPanel.add(servicePanel, "card6");

        Order.setBackground(new java.awt.Color(235, 236, 238));
        Order.setPreferredSize(new java.awt.Dimension(860, 420));

        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Time", "Price"
            }
        ));
        jScrollPane3.setViewportView(jTableOrder);

        jButtonOrderConfirm.setText("Confirm");
        jButtonOrderConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderConfirmActionPerformed(evt);
            }
        });

        jButtonOrderCancel.setText("Cancel");
        jButtonOrderCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderCancelActionPerformed(evt);
            }
        });

        jLabel18.setText("Your Order:");

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButtonOrderCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOrderConfirm)
                .addGap(82, 82, 82))
            .addGroup(OrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrderCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOrderConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        mainFlowPanel.add(Order, "orderCard");

        receiptPane.setLayout(new java.awt.CardLayout());

        requestPanel.setBackground(new java.awt.Color(235, 236, 238));

        jLabel21.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel21.setText("Your order is complete!");

        jLabel22.setText("Would you like your receipt?");

        jButton5.setText("Yes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("No");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/keycard-512.png"))); // NOI18N

        jLabel29.setText("Room card printing...");

        javax.swing.GroupLayout requestPanelLayout = new javax.swing.GroupLayout(requestPanel);
        requestPanel.setLayout(requestPanelLayout);
        requestPanelLayout.setHorizontalGroup(
            requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestPanelLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton5)
                        .addGap(101, 101, 101)
                        .addComponent(jButton6))
                    .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestPanelLayout.createSequentialGroup()
                            .addGap(307, 307, 307)
                            .addComponent(jLabel22)
                            .addGap(6, 6, 6))
                        .addGroup(requestPanelLayout.createSequentialGroup()
                            .addGap(301, 301, 301)
                            .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(requestPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(11, 11, 11))
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(0, 331, Short.MAX_VALUE))
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        requestPanelLayout.setVerticalGroup(
            requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(16, 16, 16)
                .addComponent(jLabel27)
                .addGap(34, 34, 34)
                .addComponent(jLabel22)
                .addGap(30, 30, 30)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
        );

        receiptPane.add(requestPanel, "card2");

        printPanel.setBackground(new java.awt.Color(235, 236, 238));

        jLabel24.setText("Printing receipt...");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ecommerce-Receipt-icon.png"))); // NOI18N

        javax.swing.GroupLayout printPanelLayout = new javax.swing.GroupLayout(printPanel);
        printPanel.setLayout(printPanelLayout);
        printPanelLayout.setHorizontalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printPanelLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addGroup(printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addGap(350, 350, 350))
        );
        printPanelLayout.setVerticalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel24)
                .addGap(36, 36, 36)
                .addComponent(jLabel25)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        receiptPane.add(printPanel, "card3");

        mainFlowPanel.add(receiptPane, "receiptCard");

        secondPanel.add(mainFlowPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 860, 420));

        getContentPane().add(secondPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 860, 490));
        secondPanel.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainPane.setVisible(false);
        secondPanel.setVisible(true);
        Customer.getCustomerInstance().logout();
        CardLayout c = (CardLayout)mainFlowPanel.getLayout(); 
        c.show(mainFlowPanel, "card3");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //service button
        mainPane.setVisible(false);
        CardLayout c = (CardLayout)mainFlowPanel.getLayout(); 
        c.show(mainFlowPanel, "card6");
        Customer.getCustomerInstance().logout();
        secondPanel.setVisible(true);
        
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        
        control.showDate(jCb6);
        control.showDate(jCb10);
        control.showDate(jCb11);
        control.showDate(jCb12);
        control.showDate(jCb7);
        control.showDate(jCb13);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSearchActionPerformed
        from=jCbFrom.getSelectedIndex(); 
        to=jCbTo.getSelectedIndex(); 
        control.activeSearch(jCBF, jCBT, jTableR, from, to);
    }//GEN-LAST:event_jBtSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout c = (CardLayout)mainFlowPanel.getLayout(); 
        c.show(mainFlowPanel, "card3");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtBackActionPerformed
        mainPane.setVisible(true);
    }//GEN-LAST:event_jBtBackActionPerformed

    private void jBtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConfirmActionPerformed
        if(control.ifTimeRight(jCbFrom, jCbTo, jLbWarning, from, to)){
        CardLayout c = (CardLayout)mainFlowPanel.getLayout(); 
        c.show(mainFlowPanel, "card2");
        from = jCbFrom.getSelectedIndex();           
        to = jCbTo.getSelectedIndex(); 
        try {
            control.runn(jTableR, from, to);
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jBtConfirmActionPerformed

    private void jBtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelActionPerformed
        mainPane.setVisible(true);
        secondPanel.setVisible(false);
        this.payment = null;
        
    }//GEN-LAST:event_jBtCancelActionPerformed

    private void jBtPayByCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPayByCardActionPerformed
        
        CardLayout c = (CardLayout)payPanel.getLayout(); 
        payment = new PaymentFactory().getPayMethod("PAYBYCARD");
        
        Customer.getCustomerInstance().setPayment(payment);
        payment.setOrder(order);

        jLabelTaxCard.setText(""+payment.getTax());
        jLabelCard.setText(String.format("%.2f",payment.getTotal()));
        ((PayByCard)payment).pay(jLbDeal1);
        jLbDeal1.setText(String.valueOf(order.getTotalFee()));

        c.show(payPanel, "cardPaneCard");
        Time t = new Time(500000,this);
    }//GEN-LAST:event_jBtPayByCardActionPerformed

    private void jBtPayByCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPayByCashActionPerformed
        
        CardLayout c = (CardLayout)payPanel.getLayout(); 
        payment = new PaymentFactory().getPayMethod("PAYBYCASH");
        Customer.getCustomerInstance().setPayment(payment);
        payment.setOrder(order);
        jLabelCashTotal.setText(String.format("%.2f",payment.getTotal()));
        jLabelTaxCash.setText(""+payment.getTax());
        
        ((PayByCash)payment).pay(jLbDeal);
        jLbDeal.setText(String.valueOf(order.getTotalFee()));
        
        c.show(payPanel, "cashPaneCard");
        Time t = new Time(500000,this);
    }//GEN-LAST:event_jBtPayByCashActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!Customer.getCustomerInstance().isLogedin())
            LogIn.start(2, this);
        else{
            mainPane.setVisible(false);
            secondPanel.setVisible(true);
            CardLayout c = (CardLayout)mainFlowPanel.getLayout();
            c.show(mainFlowPanel, "card5");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonRenewConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenewConfirmActionPerformed
        order.addRoom(room);
        String from1=String.valueOf(from);        
        CardLayout c = (CardLayout)mainFlowPanel.getLayout();  
        control.getRenewRoom(jTableRenew, room);
        c.show(mainFlowPanel, "orderCard");
        control.displayRenewRoom(jTableOrder, room);
    }//GEN-LAST:event_jButtonRenewConfirmActionPerformed

    private void jBtCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancel1ActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "Do you want to cancel this payment?", "", JOptionPane.YES_NO_OPTION);
        if (res == 0){
            removeFromDatabase();
            payPanel.setVisible(false);
            mainPane.setVisible(true);
            this.payment = null;
            Customer.getCustomerInstance().logout();
            DefaultTableModel model = (DefaultTableModel)(jTableOrder.getModel());
            model.setRowCount(0);
            DefaultTableModel model2 = (DefaultTableModel)(jTableRenew.getModel());
            model2.setRowCount(0);
            DefaultTableModel model3 = (DefaultTableModel)(jTableR.getModel());
            model3.setRowCount(0);
        }
        
        
    }//GEN-LAST:event_jBtCancel1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        control.confirmPay(jLabelCashTotal, jTfQuantity, jLbChange);
        
        if(Double.parseDouble(jLbChange.getText())>=0){
            JOptionPane.showMessageDialog(null,"Please collect your change :"+jLbChange.getText()+"$"," ",
                            PLAIN_MESSAGE);
            DAOFactory.getUserDAOInstance().updateAfterPayment(payment, order, Customer.getCustomerInstance());
            CardLayout c = (CardLayout)mainFlowPanel.getLayout();
            c.show(mainFlowPanel, "receiptCard");
            Customer.getCustomerInstance().logout();
            DefaultTableModel model = (DefaultTableModel)(jTableOrder.getModel());
            model.setRowCount(0);
            DefaultTableModel model2 = (DefaultTableModel)(jTableRenew.getModel());
            model2.setRowCount(0);
            DefaultTableModel model3 = (DefaultTableModel)(jTableR.getModel());
            model3.setRowCount(0);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jBtCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancel2ActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "Do you want to cancel this payment?", "", JOptionPane.YES_NO_OPTION);
        if (res == 0){
            removeFromDatabase();
            payPanel.setVisible(false);
            mainPane.setVisible(true);
            this.payment = null;
            Customer.getCustomerInstance().logout();
            //clear table
            DefaultTableModel model = (DefaultTableModel)(jTableOrder.getModel());
            model.setRowCount(0);
            DefaultTableModel model2 = (DefaultTableModel)(jTableRenew.getModel());
            model2.setRowCount(0);
            DefaultTableModel model3 = (DefaultTableModel)(jTableR.getModel());
            model3.setRowCount(0);
        }
    }//GEN-LAST:event_jBtCancel2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
            DAOFactory.getUserDAOInstance().updateAfterPayment(payment, order, Customer.getCustomerInstance());
            
            CardLayout c = (CardLayout)mainFlowPanel.getLayout();
            c.show(mainFlowPanel, "receiptCard");
            Customer.getCustomerInstance().logout();
            DefaultTableModel model = (DefaultTableModel)(jTableOrder.getModel());
            model.setRowCount(0);
            DefaultTableModel model2 = (DefaultTableModel)(jTableRenew.getModel());
            model2.setRowCount(0);
            DefaultTableModel model3 = (DefaultTableModel)(jTableR.getModel());
            model3.setRowCount(0);
            
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonOrderConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderConfirmActionPerformed
        CardLayout b = (CardLayout)mainFlowPanel.getLayout();
        CardLayout c = (CardLayout)payPanel.getLayout();
        if(Customer.getCustomerInstance().isLogedin()==false){
            LogIn.start(1, this);
        }
        else{
            //turn to payment page
            if(jTableOrder==null){
                b.show(mainFlowPanel,"payCard");
                c.show(payPanel, "paymentcard");
                insertToDatabse();
            }
            else {
                b.show(mainFlowPanel,"payCard");
                c.show(payPanel, "paymentcard");
                try {
                    from=1;
                    DAOFactory.getUserDAOInstance().updataRenewRoom(room, from, to);
                } catch (Exception ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
            
    }//GEN-LAST:event_jButtonOrderConfirmActionPerformed

    private void insertToDatabse(){
        CardLayout c = (CardLayout)mainFlowPanel.getLayout();
        try {
                //check room availability again
                System.out.println(room.getId());
//                if(DAOFactory.getUserDAOInstance().queryRoomAvailable(from, to, room.getId())){
                    //if available
                    //insert order into database
                    DAOFactory.getUserDAOInstance().insert(order);
                    //update room status
                    DAOFactory.getUserDAOInstance().update(room, from, to,"add");
//                }
//                else{
//                    //system shows error message and return to select time page
//                    JOptionPane.showMessageDialog(null,"Room has been booked, try different time!"," ",
//                            PLAIN_MESSAGE);
//                    c.show(mainFlowPanel, "card3");
//                }
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }
    
    private void removeFromDatabase(){
        try {
            //revert room status
            DAOFactory.getUserDAOInstance().update(room, from, to,"revert");
             //remove order
            DAOFactory.getUserDAOInstance().delete(order);
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void jButtonOrderCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderCancelActionPerformed
        Order.setVisible(false);
        mainPane.setVisible(true);
        customerService.clear();
        order.subtractRoom(room);
        jTableOrder.removeAll();
    }//GEN-LAST:event_jButtonOrderCancelActionPerformed

    private void jBtFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFSActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "freeServiceCard");
    }//GEN-LAST:event_jBtFSActionPerformed

    private void jBtCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCSActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "chargedCard");
    }//GEN-LAST:event_jBtCSActionPerformed

    private void jBtS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS8ActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "serviceCard");
    }//GEN-LAST:event_jBtS8ActionPerformed

    private void jBtS9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS9ActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        int res = JOptionPane.showConfirmDialog(null, "Go to the charged service?", "", JOptionPane.YES_NO_OPTION);
        if (res == 0){
            b.show(servicePanel, "chargedCard");
            }
        else {
            CardLayout c = (CardLayout)mainFlowPanel.getLayout();
            c.show(mainFlowPanel, "orderCard");
            order.addService(customerService); 
            control.displayModel(jTableOrder, customerService, Customer.getCustomerInstance().getCurrentOrder());
        }
    }//GEN-LAST:event_jBtS9ActionPerformed

    private void jCb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb12ActionPerformed

    private void jBt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt20ActionPerformed
        jPanel6.setVisible(true);
    }//GEN-LAST:event_jBt20ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        customerService = control.getService(0, customerService, jPanel6, jPanel5, jCb12, jCb7, jCb13);
        JOptionPane.showMessageDialog(null,"Services added successfully!"," ",
                PLAIN_MESSAGE);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jCb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb13ActionPerformed

    private void jCb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb7ActionPerformed

    private void jBt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt10ActionPerformed
        jPanel5.setVisible(true);
    }//GEN-LAST:event_jBt10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jBtS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS6ActionPerformed
        b =  (CardLayout)servicePanel.getLayout();
        b.show(servicePanel, "serviceCard");
    }//GEN-LAST:event_jBtS6ActionPerformed

    private void jBtS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS7ActionPerformed
        mainPane.setVisible(false);
        CardLayout c = (CardLayout)mainFlowPanel.getLayout();
        
        order.addService(customerService);
        control.displayModel(jTableOrder, customerService, order);
        c.show(mainFlowPanel, "orderCard");
    }//GEN-LAST:event_jBtS7ActionPerformed

    private void jCb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb11ActionPerformed

    private void jBt19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt19ActionPerformed
        jPanel1.setVisible(true);

    }//GEN-LAST:event_jBt19ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        customerService = control.serviceAdd(jCb, customerService, jPanel1, jPanel2, jCb11, jCb6, jCb10);
        JOptionPane.showMessageDialog(null,"Services added successfully!"," ",
                PLAIN_MESSAGE);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jCb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb10ActionPerformed

    private void jCb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb6ActionPerformed

    private void jBt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt9ActionPerformed
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jBt9ActionPerformed

    private void jBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtActionPerformed
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jBtActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        //jTableOrder.removeAll();
        CardLayout c = (CardLayout)mainFlowPanel.getLayout();
        c.show(mainFlowPanel, "orderCard");
//        String from1=String.valueOf(from);
//        control.displayRoomOrder(jTableOrder,room,from1);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jBtSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSelectActionPerformed
        control.getSelectedRoom(jTableR, room);
        order.addRoom(room);
        CardLayout c = (CardLayout)mainFlowPanel.getLayout();
        int n= JOptionPane.showConfirmDialog(null, "Do you want to book service?","Message",JOptionPane.YES_NO_OPTION);
        if(n==0){
             mainPane.setVisible(false);
 
            c.show(mainFlowPanel, "card6");

            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);

            control.showDate(jCb6);
            control.showDate(jCb10);
            control.showDate(jCb11);
            control.showDate(jCb12);
            control.showDate(jCb7);
            control.showDate(jCb13);
        }
        if(n==1){
            c.show(mainFlowPanel, "orderCard");
        }
                
        String from1=String.valueOf(jCbFrom.getSelectedItem()); 
        control.displayRoomOrder(jTableOrder,room,from1);
    }//GEN-LAST:event_jBtSelectActionPerformed

    private void jButtonRenewBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenewBackActionPerformed
        mainPane.setVisible(true);
        secondPanel.setVisible(false);
    }//GEN-LAST:event_jButtonRenewBackActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout c = (CardLayout)receiptPane.getLayout();
        c.show(receiptPane, "card3");
        
        Timer timer = new Timer();  
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                restart();
            }
        }, 3000);  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void restart(){
        new MainFrame().setVisible(true);
        this.dispose();
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        restart();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        CardLayout c = (CardLayout)payPanel.getLayout();
        c.show(payPanel, "paymentcard");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        CardLayout c = (CardLayout)payPanel.getLayout();
        c.show(payPanel, "paymentcard");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        mainPane.setVisible(true);
        secondPanel.setVisible(false);
    }//GEN-LAST:event_jLabel23MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Order;
    private javax.swing.JPanel ServicePanel;
    private javax.swing.JPanel bookRoomPane;
    private javax.swing.JPanel cardPane;
    private javax.swing.JPanel cashPane;
    private javax.swing.JPanel chargedService;
    private javax.swing.JPanel contentTopPane;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel displayPanel1;
    private javax.swing.JPanel freeService;
    private javax.swing.JButton jBt;
    private javax.swing.JButton jBt10;
    private javax.swing.JButton jBt19;
    private javax.swing.JButton jBt20;
    private javax.swing.JButton jBt9;
    private javax.swing.JButton jBtBack;
    private javax.swing.JButton jBtCS;
    private javax.swing.JButton jBtCancel;
    private javax.swing.JButton jBtCancel1;
    private javax.swing.JButton jBtCancel2;
    private javax.swing.JButton jBtConfirm;
    private javax.swing.JButton jBtFS;
    private javax.swing.JButton jBtPayByCard;
    private javax.swing.JButton jBtPayByCash;
    private javax.swing.JButton jBtS6;
    private javax.swing.JButton jBtS7;
    private javax.swing.JButton jBtS8;
    private javax.swing.JButton jBtS9;
    private javax.swing.JButton jBtSearch;
    private javax.swing.JButton jBtSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonOrderCancel;
    private javax.swing.JButton jButtonOrderConfirm;
    private javax.swing.JButton jButtonRenewBack;
    private javax.swing.JButton jButtonRenewConfirm;
    private javax.swing.JComboBox jCBF;
    private javax.swing.JComboBox jCBT;
    private javax.swing.JComboBox jCb;
    private javax.swing.JComboBox jCb10;
    private javax.swing.JComboBox jCb11;
    private javax.swing.JComboBox jCb12;
    private javax.swing.JComboBox jCb13;
    private javax.swing.JComboBox jCb6;
    private javax.swing.JComboBox jCb7;
    private javax.swing.JComboBox jCbFrom;
    private javax.swing.JComboBox jCbTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCard;
    private javax.swing.JLabel jLabelCashTotal;
    private javax.swing.JLabel jLabelTaxCard;
    private javax.swing.JLabel jLabelTaxCash;
    private javax.swing.JLabel jLbBalance;
    private javax.swing.JLabel jLbCS;
    private javax.swing.JLabel jLbChange;
    private javax.swing.JLabel jLbDeal;
    private javax.swing.JLabel jLbDeal1;
    private javax.swing.JLabel jLbWarning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTable jTableR;
    private javax.swing.JTable jTableRenew;
    private javax.swing.JTextField jTfQuantity;
    private javax.swing.JPanel mainFlowPanel;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel menuPane1;
    private javax.swing.JPanel payPanel;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JPanel printPanel;
    private javax.swing.JPanel receiptPane;
    private javax.swing.JPanel renewRoom;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JPanel secondPanel;
    private javax.swing.JPanel selectTimePanel;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JPanel topPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        //system times out return to main page
        JOptionPane.showMessageDialog(null,"System times out!"," ",
                PLAIN_MESSAGE);
        secondPanel.setVisible(true);
        mainPane.setVisible(true);
            Customer.getCustomerInstance().logout();
            DefaultTableModel model = (DefaultTableModel)(jTableOrder.getModel());
            model.setRowCount(0);
            DefaultTableModel model2 = (DefaultTableModel)(jTableRenew.getModel());
            model2.setRowCount(0);
            DefaultTableModel model3 = (DefaultTableModel)(jTableR.getModel());
            model3.setRowCount(0);
    }

    @Override
    public void update(int i) {
        if(i==1){
            //turn to payment page
            secondPanel.setVisible(true);
            mainFlowPanel.setVisible(true);
            CardLayout c = (CardLayout)mainFlowPanel.getLayout();
            c.show(mainFlowPanel, "payCard");
            insertToDatabse();
        }
        if(i==2){
            //turn to renew room page
            
            mainPane.setVisible(false);
            secondPanel.setVisible(true);
            mainFlowPanel.setVisible(true);
            CardLayout c = (CardLayout)mainFlowPanel.getLayout();
            c.show(mainFlowPanel, "card5");
            try {
                control.renewRoom(jTableRenew, Customer.getCustomerInstance().getUserName());
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
    }
}
