/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UI.SelectTimeSlot;
import UI.SelectTimeSlot;
import UI.SelectTimeSlot;
import hotelpossystem.Order;
import hotelpossystem.Service;
import hotelpossystem.dao.DAOFactory;
import hotelpossystem.dao.UserDAOImplement;
import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shuang
 */
public class ServiceFrame extends javax.swing.JFrame {
    CardLayout c;
    Order order = new Order();
    ArrayList <Service> customerService;
    ArrayList <Service> services;
    

    

    /**
     * Creates new form ServiceFrame
     */
    public ServiceFrame() {
        initComponents();
        c = (CardLayout)getContentPane().getLayout();
        try {
            DAOFactory.getUserDAOInstance().queryGetService();
        } catch (Exception ex) {
            Logger.getLogger(ServiceFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ServicePanel = new javax.swing.JPanel();
        jBtFS = new javax.swing.JButton();
        jBtCS = new javax.swing.JButton();
        freeService = new javax.swing.JPanel();
        jLbMC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBtS1 = new javax.swing.JButton();
        jBtS8 = new javax.swing.JButton();
        jBtS9 = new javax.swing.JButton();
        chargedService = new javax.swing.JPanel();
        jLbCS = new javax.swing.JLabel();
        jBtS6 = new javax.swing.JButton();
        jBtS7 = new javax.swing.JButton();
        jBt1 = new javax.swing.JButton();
        jBt3 = new javax.swing.JButton();
        jBt4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCb7 = new javax.swing.JComboBox();
        jCb9 = new javax.swing.JComboBox();
        jCb10 = new javax.swing.JComboBox();
        jBt13 = new javax.swing.JButton();
        jLb7 = new javax.swing.JLabel();
        jBt14 = new javax.swing.JButton();
        jBt15 = new javax.swing.JButton();
        jLb8 = new javax.swing.JLabel();
        jBt16 = new javax.swing.JButton();
        jBt17 = new javax.swing.JButton();
        jLb9 = new javax.swing.JLabel();
        jBt18 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCb11 = new javax.swing.JComboBox();
        jCb12 = new javax.swing.JComboBox();
        jCb13 = new javax.swing.JComboBox();
        jBt19 = new javax.swing.JButton();
        jLb10 = new javax.swing.JLabel();
        jBt20 = new javax.swing.JButton();
        jBt21 = new javax.swing.JButton();
        jLb11 = new javax.swing.JLabel();
        jBt22 = new javax.swing.JButton();
        jBt23 = new javax.swing.JButton();
        jLb12 = new javax.swing.JLabel();
        jBt24 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCb5 = new javax.swing.JComboBox();
        jCb6 = new javax.swing.JComboBox();
        jCb8 = new javax.swing.JComboBox();
        jBt2 = new javax.swing.JButton();
        jLb1 = new javax.swing.JLabel();
        jBt5 = new javax.swing.JButton();
        jBt9 = new javax.swing.JButton();
        jLb5 = new javax.swing.JLabel();
        jBt10 = new javax.swing.JButton();
        jBt11 = new javax.swing.JButton();
        jLb6 = new javax.swing.JLabel();
        jBt12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jBt25 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCb14 = new javax.swing.JComboBox();
        jCb15 = new javax.swing.JComboBox();
        jCb16 = new javax.swing.JComboBox();
        jBt26 = new javax.swing.JButton();
        jLb13 = new javax.swing.JLabel();
        jBt27 = new javax.swing.JButton();
        jBt28 = new javax.swing.JButton();
        jLb14 = new javax.swing.JLabel();
        jBt29 = new javax.swing.JButton();
        jBt30 = new javax.swing.JButton();
        jLb15 = new javax.swing.JLabel();
        jBt31 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Order = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dateWindow(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jBtFS.setText("Free Service");
        jBtFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFSActionPerformed(evt);
            }
        });

        jBtCS.setText("Charged Service");
        jBtCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicePanelLayout = new javax.swing.GroupLayout(ServicePanel);
        ServicePanel.setLayout(ServicePanelLayout);
        ServicePanelLayout.setHorizontalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBtFS, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 753, Short.MAX_VALUE)
                .addComponent(jBtCS, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        ServicePanelLayout.setVerticalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicePanelLayout.createSequentialGroup()
                .addContainerGap(514, Short.MAX_VALUE)
                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtCS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtFS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        getContentPane().add(ServicePanel, "card2");

        jLbMC.setText("Morning Call");

        jLabel7.setText("Free Service");

        jBtS1.setText("Select");
        jBtS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS1ActionPerformed(evt);
            }
        });

        jBtS8.setText("Back");
        jBtS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS8ActionPerformed(evt);
            }
        });

        jBtS9.setText("Next");

        javax.swing.GroupLayout freeServiceLayout = new javax.swing.GroupLayout(freeService);
        freeService.setLayout(freeServiceLayout);
        freeServiceLayout.setHorizontalGroup(
            freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(freeServiceLayout.createSequentialGroup()
                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(freeServiceLayout.createSequentialGroup()
                        .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(freeServiceLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLbMC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jBtS1))
                            .addGroup(freeServiceLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 694, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, freeServiceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtS8)
                        .addGap(26, 26, 26)))
                .addComponent(jBtS9)
                .addGap(29, 29, 29))
        );
        freeServiceLayout.setVerticalGroup(
            freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(freeServiceLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbMC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtS1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtS8)
                    .addComponent(jBtS9))
                .addGap(36, 36, 36))
        );

        getContentPane().add(freeService, "card3");

        jLbCS.setText("Charged Service");

        jBtS6.setText("Back");
        jBtS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS6ActionPerformed(evt);
            }
        });

        jBtS7.setText("Next");
        jBtS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS7ActionPerformed(evt);
            }
        });

        jBt1.setText("+");
        jBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt1ActionPerformed(evt);
            }
        });

        jBt3.setText("+");
        jBt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt3ActionPerformed(evt);
            }
        });

        jBt4.setText("+");
        jBt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt4ActionPerformed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb7ActionPerformed(evt);
            }
        });

        jCb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb9ActionPerformed(evt);
            }
        });

        jCb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb10ActionPerformed(evt);
            }
        });

        jBt13.setText("+");
        jBt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt13ActionPerformed(evt);
            }
        });

        jLb7.setText("0");

        jBt14.setText("-");
        jBt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt14ActionPerformed(evt);
            }
        });

        jBt15.setText("+");
        jBt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt15ActionPerformed(evt);
            }
        });

        jLb8.setText("0");

        jBt16.setText("-");
        jBt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt16ActionPerformed(evt);
            }
        });

        jBt17.setText("+");
        jBt17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt17ActionPerformed(evt);
            }
        });

        jLb9.setText("0");

        jBt18.setText("-");
        jBt18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt18ActionPerformed(evt);
            }
        });

        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCb9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBt13)
                    .addComponent(jBt15)
                    .addComponent(jBt17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb7)
                    .addComponent(jLb8)
                    .addComponent(jLb9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBt14)
                    .addComponent(jBt16)
                    .addComponent(jBt18))
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt13)
                    .addComponent(jLb7)
                    .addComponent(jBt14))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt15)
                    .addComponent(jLb8)
                    .addComponent(jBt16))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt17)
                    .addComponent(jLb9)
                    .addComponent(jBt18))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb11ActionPerformed(evt);
            }
        });

        jCb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb12ActionPerformed(evt);
            }
        });

        jCb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb13ActionPerformed(evt);
            }
        });

        jBt19.setText("+");
        jBt19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt19ActionPerformed(evt);
            }
        });

        jLb10.setText("0");

        jBt20.setText("-");
        jBt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt20ActionPerformed(evt);
            }
        });

        jBt21.setText("+");
        jBt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt21ActionPerformed(evt);
            }
        });

        jLb11.setText("0");

        jBt22.setText("-");
        jBt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt22ActionPerformed(evt);
            }
        });

        jBt23.setText("+");
        jBt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt23ActionPerformed(evt);
            }
        });

        jLb12.setText("0");

        jBt24.setText("-");
        jBt24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt24ActionPerformed(evt);
            }
        });

        jButton5.setText("Confirm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCb13, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCb11, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCb12, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBt21)
                                .addGap(0, 0, 0)
                                .addComponent(jLb11)
                                .addGap(0, 0, 0)
                                .addComponent(jBt22))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBt19)
                                .addGap(0, 0, 0)
                                .addComponent(jLb10)
                                .addGap(0, 0, 0)
                                .addComponent(jBt20))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBt23)
                                .addGap(0, 0, 0)
                                .addComponent(jLb12)
                                .addGap(0, 0, 0)
                                .addComponent(jBt24))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBt19)
                    .addComponent(jBt20)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLb10))
                    .addComponent(jCb11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBt21)
                        .addComponent(jCb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLb11))
                    .addComponent(jBt22))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBt23)
                        .addComponent(jCb12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLb12))
                    .addComponent(jBt24))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb5ActionPerformed(evt);
            }
        });

        jCb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb6ActionPerformed(evt);
            }
        });

        jCb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb8ActionPerformed(evt);
            }
        });

        jBt2.setText("+");
        jBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt2ActionPerformed(evt);
            }
        });

        jLb1.setText("0");

        jBt5.setText("-");
        jBt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt5ActionPerformed(evt);
            }
        });

        jBt9.setText("+");
        jBt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt9ActionPerformed(evt);
            }
        });

        jLb5.setText("0");

        jBt10.setText("-");
        jBt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt10ActionPerformed(evt);
            }
        });

        jBt11.setText("+");
        jBt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt11ActionPerformed(evt);
            }
        });

        jLb6.setText("0");

        jBt12.setText("-");
        jBt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt12ActionPerformed(evt);
            }
        });

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1)
                        .addGap(6, 6, 6)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBt11)
                            .addComponent(jBt9)
                            .addComponent(jBt2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLb1)
                            .addComponent(jLb5)
                            .addComponent(jLb6))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBt12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBt5)
                            .addComponent(jBt10))))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBt11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLb1))
                                    .addComponent(jBt5))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLb5))
                                    .addComponent(jBt10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBt2)
                                .addGap(24, 24, 24)
                                .addComponent(jBt9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLb6))
                            .addComponent(jBt12))))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButton7.setText("Breakfast");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Lunch");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Laundry");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Super");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jBt25.setText("+");
        jBt25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt25ActionPerformed(evt);
            }
        });

        jPanel4.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb14ActionPerformed(evt);
            }
        });

        jCb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb15ActionPerformed(evt);
            }
        });

        jCb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb16ActionPerformed(evt);
            }
        });

        jBt26.setText("+");
        jBt26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt26ActionPerformed(evt);
            }
        });

        jLb13.setText("0");

        jBt27.setText("-");
        jBt27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt27ActionPerformed(evt);
            }
        });

        jBt28.setText("+");
        jBt28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt28ActionPerformed(evt);
            }
        });

        jLb14.setText("0");

        jBt29.setText("-");
        jBt29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt29ActionPerformed(evt);
            }
        });

        jBt30.setText("+");
        jBt30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt30ActionPerformed(evt);
            }
        });

        jLb15.setText("0");

        jBt31.setText("-");
        jBt31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt31ActionPerformed(evt);
            }
        });

        jButton11.setText("Confirm");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Cancel");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCb16, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCb14, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCb15, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jBt28)
                                .addGap(0, 0, 0)
                                .addComponent(jLb14)
                                .addGap(0, 0, 0)
                                .addComponent(jBt29))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jBt26)
                                .addGap(0, 0, 0)
                                .addComponent(jLb13)
                                .addGap(0, 0, 0)
                                .addComponent(jBt27))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jBt30)
                                .addGap(0, 0, 0)
                                .addComponent(jLb15)
                                .addGap(0, 0, 0)
                                .addComponent(jBt31))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBt26)
                    .addComponent(jBt27)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLb13))
                    .addComponent(jCb14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBt28)
                        .addComponent(jCb16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLb14))
                    .addComponent(jBt29))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBt30)
                        .addComponent(jCb15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLb15))
                    .addComponent(jBt31))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chargedServiceLayout = new javax.swing.GroupLayout(chargedService);
        chargedService.setLayout(chargedServiceLayout);
        chargedServiceLayout.setHorizontalGroup(
            chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chargedServiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtS6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtS7)
                .addGap(243, 243, 243))
            .addGroup(chargedServiceLayout.createSequentialGroup()
                .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chargedServiceLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chargedServiceLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(chargedServiceLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10)
                                    .addComponent(jButton8)
                                    .addComponent(jButton9)))
                            .addComponent(jButton7))
                        .addGap(48, 48, 48)
                        .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBt1)
                            .addComponent(jBt3)
                            .addComponent(jBt4)
                            .addComponent(jBt25)))
                    .addGroup(chargedServiceLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLbCS, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chargedServiceLayout.createSequentialGroup()
                    .addGap(378, 378, 378)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(378, Short.MAX_VALUE)))
            .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chargedServiceLayout.createSequentialGroup()
                    .addGap(378, 378, 378)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(378, Short.MAX_VALUE)))
        );
        chargedServiceLayout.setVerticalGroup(
            chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chargedServiceLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLbCS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chargedServiceLayout.createSequentialGroup()
                        .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(chargedServiceLayout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9))
                            .addGroup(chargedServiceLayout.createSequentialGroup()
                                .addComponent(jBt4)
                                .addGap(18, 18, 18)
                                .addComponent(jBt3)
                                .addGap(18, 18, 18)
                                .addComponent(jBt1)
                                .addGap(18, 18, 18)
                                .addComponent(jBt25)))
                        .addGap(65, 65, 65)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtS6)
                    .addComponent(jBtS7))
                .addGap(37, 37, 37))
            .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chargedServiceLayout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
            .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chargedServiceLayout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        getContentPane().add(chargedService, "card4");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service", "Time", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(581, Short.MAX_VALUE))
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        getContentPane().add(Order, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFSActionPerformed
        c.show(getContentPane(), "card3");
    }//GEN-LAST:event_jBtFSActionPerformed

    private void jBtCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCSActionPerformed
        c.show(getContentPane(), "card4");
    }//GEN-LAST:event_jBtCSActionPerformed

    private void jBtS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS8ActionPerformed
        c.show(getContentPane(), "card2");
    }//GEN-LAST:event_jBtS8ActionPerformed

    private void dateWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dateWindow
        showDate(jCb5);
        showDate(jCb6);
        showDate(jCb7);
        showDate(jCb8);
        showDate(jCb9);
        showDate(jCb10);
        showDate(jCb11);
        showDate(jCb12);
        showDate(jCb13);
        showDate(jCb14);
        showDate(jCb15);
        showDate(jCb16);

    }//GEN-LAST:event_dateWindow

    public void showDate(JComboBox jCb) {
        Date dt = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
        String today = sf.format(dt);
        String[] next = new String[6];
        Calendar cal = Calendar.getInstance();
        jCb.addItem(today);

        for (int i = 0; i < 6; i++) {
            try {
                cal.setTime(sf.parse(today));
            } catch (ParseException ex) {
                Logger.getLogger(SelectTimeSlot.class.getName()).log(Level.SEVERE, null, ex);
            }
            cal.add(Calendar.DAY_OF_YEAR, +(i+1));
            next[i] = sf.format(cal.getTime());
            jCb.addItem(next[i]);
        }
    }
    
    
    
    private void jBtS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS1ActionPerformed
        customerService.add(services.get(1));
    }//GEN-LAST:event_jBtS1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jCb5.getSelectedIndex() == jCb6.getSelectedIndex() || jCb5.getSelectedIndex() == jCb7.getSelectedIndex() || jCb6.getSelectedIndex() == jCb7.getSelectedIndex())
            JOptionPane.showMessageDialog(jPanel1, "You cannot choose the same date");
        
        if (jLb1.getText().equals("1")) {
            Service br = (Service) services.get(2);
            Date date = (Date)jCb5.getSelectedItem();
            br.setDate(date);
            customerService.add(br);
        }
        if (jLb5.getText().equals("1")) {
            Service br = (Service) services.get(2);
            Date date = (Date)jCb6.getSelectedItem();
            br.setDate(date);
            customerService.add(br);
        }
        if (jLb6.getText().equals("1")) {
            Service br = (Service) services.get(2);
            Date date = (Date)jCb8.getSelectedItem();
            br.setDate(date);
            customerService.add(br);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt12ActionPerformed
        setLabel(jLb6, 0);
    }//GEN-LAST:event_jBt12ActionPerformed

    private void jBt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt11ActionPerformed
        setLabel(jLb6, 1);
    }//GEN-LAST:event_jBt11ActionPerformed

    private void jBt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt10ActionPerformed
        setLabel(jLb5, 0);
    }//GEN-LAST:event_jBt10ActionPerformed

    private void jBt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt9ActionPerformed
        setLabel(jLb5, 1);
    }//GEN-LAST:event_jBt9ActionPerformed

    private void jBt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt5ActionPerformed
        setLabel(jLb1, 0);
    }//GEN-LAST:event_jBt5ActionPerformed

    private void jBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt2ActionPerformed
        jLb1.setText("1");
    }//GEN-LAST:event_jBt2ActionPerformed

    private void jCb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb8ActionPerformed

    private void jCb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb6ActionPerformed

    private void jCb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb5ActionPerformed

    }//GEN-LAST:event_jCb5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jCb7.getSelectedIndex() == jCb9.getSelectedIndex() || jCb7.getSelectedIndex() == jCb10.getSelectedIndex() || jCb9.getSelectedIndex() == jCb10.getSelectedIndex())
            JOptionPane.showMessageDialog(jPanel2, "You cannot choose the same date");
        if (jLb7.getText().equals("1")) {
            Service br = (Service) services.get(3);
            Date date = (Date)jCb7.getSelectedItem();
            br.setDate(date);
            customerService.add(br);
        }
        if (jLb8.getText().equals("1")) {
            Service br = (Service) services.get(3);
            Date date = (Date)jCb9.getSelectedItem();
            br.setDate(date);
            customerService.add(br);
        }
        if (jLb9.getText().equals("1")) {
            Service br = (Service) services.get(3);
            Date date = (Date)jCb10.getSelectedItem();
            br.setDate(date);
            customerService.add(br);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBt18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt18ActionPerformed
        setLabel(jLb9, 0);
    }//GEN-LAST:event_jBt18ActionPerformed

    private void jBt17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt17ActionPerformed
        setLabel(jLb9, 1);
    }//GEN-LAST:event_jBt17ActionPerformed

    private void jBt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt16ActionPerformed
        setLabel(jLb8, 0);
    }//GEN-LAST:event_jBt16ActionPerformed

    private void jBt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt15ActionPerformed
        setLabel(jLb8, 1);
    }//GEN-LAST:event_jBt15ActionPerformed

    private void jBt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt14ActionPerformed
        setLabel(jLb7, 0);
    }//GEN-LAST:event_jBt14ActionPerformed

    private void jBt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt13ActionPerformed
        setLabel(jLb7, 1);
    }//GEN-LAST:event_jBt13ActionPerformed

    private void jCb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb10ActionPerformed

    private void jCb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb9ActionPerformed

    private void jCb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jCb11.getSelectedIndex() == jCb12.getSelectedIndex() || jCb11.getSelectedIndex() == jCb13.getSelectedIndex() || jCb12.getSelectedIndex() == jCb13.getSelectedIndex())
            JOptionPane.showMessageDialog(jPanel3, "You cannot choose the same date");                

        if (jLb10.getText().equals("1")) {
            Service su = (Service) services.get(4);
            Date date = (Date)jCb11.getSelectedItem();
            su.setDate(date);
            customerService.add(su);
        }
        if (jLb11.getText().equals("1")) {
            Service su = (Service) services.get(4);
            Date date = (Date)jCb12.getSelectedItem();
            su.setDate(date);
            customerService.add(su);
        }
        if (jLb12.getText().equals("1")) {
            Service su = (Service) services.get(4);
            Date date = (Date)jCb13.getSelectedItem();
            su.setDate(date);
            customerService.add(su);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBt24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt24ActionPerformed
        setLabel(jLb12, 0);
    }//GEN-LAST:event_jBt24ActionPerformed

    private void jBt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt23ActionPerformed
        setLabel(jLb12, 1);
    }//GEN-LAST:event_jBt23ActionPerformed

    private void jBt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt22ActionPerformed
        setLabel(jLb11, 0);
    }//GEN-LAST:event_jBt22ActionPerformed

    private void jBt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt21ActionPerformed
        setLabel(jLb11, 1);
    }//GEN-LAST:event_jBt21ActionPerformed

    private void jBt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt20ActionPerformed
        setLabel(jLb10, 0);
    }//GEN-LAST:event_jBt20ActionPerformed

    private void jBt19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt19ActionPerformed
        setLabel(jLb10, 1);
    }//GEN-LAST:event_jBt19ActionPerformed

    private void jCb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb13ActionPerformed

    private void jCb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb12ActionPerformed

    private void jCb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb11ActionPerformed

    private void jBt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt4ActionPerformed
        Service lu = (Service) services.get(2);
        Date date = (Date)jCb5.getSelectedItem();
        lu.setDate(date);
        customerService.add(lu);
    }//GEN-LAST:event_jBt4ActionPerformed

    private void jBt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt3ActionPerformed
        Service su = (Service) services.get(2);
        Date date = (Date)jCb5.getSelectedItem();
        su.setDate(date);
        customerService.add(su);
    }//GEN-LAST:event_jBt3ActionPerformed

    private void jBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt1ActionPerformed
        Service la = (Service) services.get(2);
        Date date = (Date)jCb5.getSelectedItem();
        la.setDate(date);
        customerService.add(la);
    }//GEN-LAST:event_jBt1ActionPerformed

    private void jBtS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS6ActionPerformed
        c.show(getContentPane(), "card2");
    }//GEN-LAST:event_jBtS6ActionPerformed

    private void jBt25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBt25ActionPerformed

    private void jCb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb14ActionPerformed

    private void jCb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb15ActionPerformed

    private void jCb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb16ActionPerformed

    private void jBt26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt26ActionPerformed
        setLabel(jLb13, 1);
    }//GEN-LAST:event_jBt26ActionPerformed

    private void jBt27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt27ActionPerformed
        setLabel(jLb13,0);
    }//GEN-LAST:event_jBt27ActionPerformed

    private void jBt28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt28ActionPerformed
        setLabel(jLb14,1);
    }//GEN-LAST:event_jBt28ActionPerformed

    private void jBt29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt29ActionPerformed
        setLabel(jLb14,0);
    }//GEN-LAST:event_jBt29ActionPerformed

    private void jBt30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt30ActionPerformed
        setLabel(jLb15,1);
    }//GEN-LAST:event_jBt30ActionPerformed

    private void jBt31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt31ActionPerformed
        setLabel(jLb15,0);
    }//GEN-LAST:event_jBt31ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        if (jCb14.getSelectedIndex() == jCb15.getSelectedIndex() || jCb15.getSelectedIndex() == jCb16.getSelectedIndex() || jCb14.getSelectedIndex() == jCb16.getSelectedIndex())
            JOptionPane.showMessageDialog(jPanel4, "You cannot choose the same date");
        if (jLb13.getText().equals("1")) {
            Service su = (Service) services.get(4);
            Date date = (Date)jCb14.getSelectedItem();
            su.setDate(date);
            customerService.add(su);
        }
        if (jLb14.getText().equals("1")) {
            Service su = (Service) services.get(4);
            Date date = (Date)jCb15.getSelectedItem();
            su.setDate(date);
            customerService.add(su);
        }
        if (jLb15.getText().equals("1")) {
            Service su = (Service) services.get(4);
            Date date = (Date)jCb16.getSelectedItem();
            su.setDate(date);
            customerService.add(su);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jBtS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS7ActionPerformed
        order.addService(customerService);
    }//GEN-LAST:event_jBtS7ActionPerformed
    
    public static void setLabel(JLabel jLb, int i) {
        if (i == 1)
            jLb.setText("1");
        else if (i == 0)
            jLb.setText("0");
        else
            System.out.println("Error: wrong input!");
    }
    
    
    public void displayModel() throws SQLException {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            Object[] object = new Object[3];
            //service name; service time; service price; total;
            for (Service s : customerService) {
                object[0] = s.getName();
                object[1] = s.getDate();
                object[2] = s.getPrice();
            }
            model.addRow(object);
            object[0] = null;
            object[1] = null;
            object[2] = order.getTotalFee();
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServiceFrame sf = new ServiceFrame();
                sf.setVisible(true);
                sf.jPanel1.setVisible(false);
                sf.jPanel2.setVisible(false);
                sf.jPanel3.setVisible(false);
                sf.jPanel4.setVisible(false);
                
                try {
                    //sf.services = DAOFactory.getUserDAOInstance().queryGetService();
                } catch (Exception ex) {
                    Logger.getLogger(ServiceFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Order;
    private javax.swing.JPanel ServicePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel chargedService;
    private javax.swing.JPanel freeService;
    private javax.swing.JButton jBt1;
    private javax.swing.JButton jBt10;
    private javax.swing.JButton jBt11;
    private javax.swing.JButton jBt12;
    private javax.swing.JButton jBt13;
    private javax.swing.JButton jBt14;
    private javax.swing.JButton jBt15;
    private javax.swing.JButton jBt16;
    private javax.swing.JButton jBt17;
    private javax.swing.JButton jBt18;
    private javax.swing.JButton jBt19;
    private javax.swing.JButton jBt2;
    private javax.swing.JButton jBt20;
    private javax.swing.JButton jBt21;
    private javax.swing.JButton jBt22;
    private javax.swing.JButton jBt23;
    private javax.swing.JButton jBt24;
    private javax.swing.JButton jBt25;
    private javax.swing.JButton jBt26;
    private javax.swing.JButton jBt27;
    private javax.swing.JButton jBt28;
    private javax.swing.JButton jBt29;
    private javax.swing.JButton jBt3;
    private javax.swing.JButton jBt30;
    private javax.swing.JButton jBt31;
    private javax.swing.JButton jBt4;
    private javax.swing.JButton jBt5;
    private javax.swing.JButton jBt9;
    private javax.swing.JButton jBtCS;
    private javax.swing.JButton jBtFS;
    private javax.swing.JButton jBtS1;
    private javax.swing.JButton jBtS6;
    private javax.swing.JButton jBtS7;
    private javax.swing.JButton jBtS8;
    private javax.swing.JButton jBtS9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCb10;
    private javax.swing.JComboBox jCb11;
    private javax.swing.JComboBox jCb12;
    private javax.swing.JComboBox jCb13;
    private javax.swing.JComboBox jCb14;
    private javax.swing.JComboBox jCb15;
    private javax.swing.JComboBox jCb16;
    private javax.swing.JComboBox jCb5;
    private javax.swing.JComboBox jCb6;
    private javax.swing.JComboBox jCb7;
    private javax.swing.JComboBox jCb8;
    private javax.swing.JComboBox jCb9;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLb1;
    private javax.swing.JLabel jLb10;
    private javax.swing.JLabel jLb11;
    private javax.swing.JLabel jLb12;
    private javax.swing.JLabel jLb13;
    private javax.swing.JLabel jLb14;
    private javax.swing.JLabel jLb15;
    private javax.swing.JLabel jLb5;
    private javax.swing.JLabel jLb6;
    private javax.swing.JLabel jLb7;
    private javax.swing.JLabel jLb8;
    private javax.swing.JLabel jLb9;
    private javax.swing.JLabel jLbCS;
    private javax.swing.JLabel jLbMC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
