/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import hotelpossystem.Order;
import hotelpossystem.Service;
import hotelpossystem.dao.DAOFactory;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import UI.LogIn;
import UI.LogIn;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Shuang
 */
public class ServiceFrame2 extends javax.swing.JFrame {
    CardLayout c;
    Order order = new Order();
    ArrayList <Service> customerService = new ArrayList();
    Control control = new Control();
    
    

    /**
     * Creates new form ServiceFrame
     */
    public ServiceFrame2() {
        initComponents();
        c = (CardLayout)getContentPane().getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ServicePanel = new javax.swing.JPanel();
        jBtFS = new javax.swing.JButton();
        jBtCS = new javax.swing.JButton();
        freeService = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jBtS8 = new javax.swing.JButton();
        jBtS9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCb12 = new javax.swing.JComboBox();
        jBt20 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jCb13 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jCb7 = new javax.swing.JComboBox();
        jBt10 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chargedService = new javax.swing.JPanel();
        jLbCS = new javax.swing.JLabel();
        jBtS6 = new javax.swing.JButton();
        jBtS7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCb11 = new javax.swing.JComboBox();
        jBt19 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCb10 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jCb6 = new javax.swing.JComboBox();
        jBt9 = new javax.swing.JButton();
        jCb = new javax.swing.JComboBox();
        jBt = new javax.swing.JButton();
        Order = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dateWindow(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jBtFS.setText("Free Service");
        jBtFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFSActionPerformed(evt);
            }
        });

        jBtCS.setText("Charged Service");
        jBtCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicePanelLayout = new javax.swing.GroupLayout(ServicePanel);
        ServicePanel.setLayout(ServicePanelLayout);
        ServicePanelLayout.setHorizontalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBtFS, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(jBtCS, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        ServicePanelLayout.setVerticalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicePanelLayout.createSequentialGroup()
                .addContainerGap(535, Short.MAX_VALUE)
                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtCS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtFS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        getContentPane().add(ServicePanel, "card2");

        jLabel7.setText("Free Service");

        jBtS8.setText("Back");
        jBtS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS8ActionPerformed(evt);
            }
        });

        jBtS9.setText("Next");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setPreferredSize(new java.awt.Dimension(350, 300));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb12ActionPerformed(evt);
            }
        });
        jPanel4.add(jCb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jBt20.setText("+");
        jBt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt20ActionPerformed(evt);
            }
        });
        jPanel4.add(jBt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton7.setText("Confirm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jButton8.setText("Cancel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jPanel5.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jCb13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 260, 60));

        jPanel6.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb7ActionPerformed(evt);
            }
        });

        jBt10.setText("+");
        jBt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBt10)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt10))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 64));

        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Morning Call");

        javax.swing.GroupLayout freeServiceLayout = new javax.swing.GroupLayout(freeService);
        freeService.setLayout(freeServiceLayout);
        freeServiceLayout.setHorizontalGroup(
            freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(freeServiceLayout.createSequentialGroup()
                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, freeServiceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtS8)
                        .addGap(26, 26, 26))
                    .addGroup(freeServiceLayout.createSequentialGroup()
                        .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(freeServiceLayout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(freeServiceLayout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2)))
                            .addGroup(freeServiceLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)))
                .addComponent(jBtS9)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, freeServiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(169, 169, 169))
        );
        freeServiceLayout.setVerticalGroup(
            freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(freeServiceLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(137, 137, 137)
                .addGroup(freeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtS8)
                    .addComponent(jBtS9))
                .addGap(36, 36, 36))
        );

        getContentPane().add(freeService, "card3");

        jLbCS.setText("Charged Service");

        jBtS6.setText("Back");
        jBtS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS6ActionPerformed(evt);
            }
        });

        jBtS7.setText("Next");
        jBtS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtS7ActionPerformed(evt);
            }
        });

        jPanel3.setPreferredSize(new java.awt.Dimension(350, 300));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb11ActionPerformed(evt);
            }
        });
        jPanel3.add(jCb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jBt19.setText("+");
        jBt19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt19ActionPerformed(evt);
            }
        });
        jPanel3.add(jBt19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton5.setText("Confirm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jCb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 260, 60));

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 300));

        jCb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb6ActionPerformed(evt);
            }
        });

        jBt9.setText("+");
        jBt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBt9)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt9))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 64));

        jCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Breakfast", "Lunch", "Super", "Laundry" }));

        jBt.setText("Choose");
        jBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chargedServiceLayout = new javax.swing.GroupLayout(chargedService);
        chargedService.setLayout(chargedServiceLayout);
        chargedServiceLayout.setHorizontalGroup(
            chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chargedServiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtS6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtS7)
                .addGap(243, 243, 243))
            .addGroup(chargedServiceLayout.createSequentialGroup()
                .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chargedServiceLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chargedServiceLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBt))
                    .addGroup(chargedServiceLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLbCS, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        chargedServiceLayout.setVerticalGroup(
            chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chargedServiceLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLbCS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt))
                .addGap(121, 121, 121)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(chargedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtS6)
                    .addComponent(jBtS7))
                .addGap(37, 37, 37))
        );

        getContentPane().add(chargedService, "card4");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service", "Time", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton13.setText("Confirm");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Cancel");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(37, 37, 37)
                        .addComponent(jButton14))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(Order, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFSActionPerformed
        c.show(getContentPane(), "card3");
    }//GEN-LAST:event_jBtFSActionPerformed

    private void jBtCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCSActionPerformed
        c.show(getContentPane(), "card4");
    }//GEN-LAST:event_jBtCSActionPerformed

    private void jBtS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS8ActionPerformed
        c.show(getContentPane(), "card2");
    }//GEN-LAST:event_jBtS8ActionPerformed

    private void dateWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dateWindow
        control.showDate(jCb6);
        control.showDate(jCb10);
        control.showDate(jCb11);
        control.showDate(jCb12);
        control.showDate(jCb7);
        control.showDate(jCb13);
    }//GEN-LAST:event_dateWindow

    
    private void jBt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt9ActionPerformed
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jBt9ActionPerformed

    private void jCb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb6ActionPerformed

    private void jCb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        customerService = control.serviceAdd(jCb, customerService, jPanel1, jPanel2, jCb11, jCb6, jCb10);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

            
    
 
    
    private void jBt19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt19ActionPerformed
        jPanel1.setVisible(true);
        
    }//GEN-LAST:event_jBt19ActionPerformed

    
    
    private void jCb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb11ActionPerformed

    private void jBtS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS6ActionPerformed
        c.show(getContentPane(), "card2");
    }//GEN-LAST:event_jBtS6ActionPerformed

    private void jBtS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtS7ActionPerformed
        c.show(getContentPane(), "card5");
        order.addService(customerService);
        control.displayModel(jTable1, customerService, order); 
    }//GEN-LAST:event_jBtS7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       new LogIn().setVisible(true);
       
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        c.show(getContentPane(), "card2");
        customerService.clear();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtActionPerformed
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jBtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c.show(getContentPane(), "card2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb12ActionPerformed

    private void jBt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt20ActionPerformed
        jPanel6.setVisible(true);
    }//GEN-LAST:event_jBt20ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        customerService = control.getService(0, customerService, jPanel6, jPanel5, jCb12, jCb7, jCb13);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jCb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb13ActionPerformed

    private void jCb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCb7ActionPerformed

    private void jBt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt10ActionPerformed
        jPanel5.setVisible(true);
    }//GEN-LAST:event_jBt10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServiceFrame2 sf = new ServiceFrame2();
                sf.setVisible(true);
                sf.jPanel1.setVisible(false);
                sf.jPanel2.setVisible(false);
                sf.jPanel3.setVisible(false);
                sf.jPanel4.setVisible(false);
                sf.jPanel5.setVisible(false);
                sf.jPanel6.setVisible(false);
                
                
                try {
                    //sf.services = DAOFactory.getUserDAOInstance().queryGetService();
                } catch (Exception ex) {
                    Logger.getLogger(ServiceFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Order;
    private javax.swing.JPanel ServicePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel chargedService;
    private javax.swing.JPanel freeService;
    private javax.swing.JButton jBt;
    private javax.swing.JButton jBt10;
    private javax.swing.JButton jBt19;
    private javax.swing.JButton jBt20;
    private javax.swing.JButton jBt9;
    private javax.swing.JButton jBtCS;
    private javax.swing.JButton jBtFS;
    private javax.swing.JButton jBtS6;
    private javax.swing.JButton jBtS7;
    private javax.swing.JButton jBtS8;
    private javax.swing.JButton jBtS9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jCb;
    private javax.swing.JComboBox jCb10;
    private javax.swing.JComboBox jCb11;
    private javax.swing.JComboBox jCb12;
    private javax.swing.JComboBox jCb13;
    private javax.swing.JComboBox jCb6;
    private javax.swing.JComboBox jCb7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLbCS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
